fd1d_heat_explicit_prb – 1D heat equation
fd1d_heat_explicit_prb Program
110 statements
Source File
Uses
Types_mod
RHS_mod
CFL_mod
IO_mod
Solver_mod
, Solves the one dimensional heat diffusion equation
Calls
Contents
Variables
T_NUM X_NUM cfl dt h ierr_h msg_h h_new ierr_h_new msg_h_new hmat ierr_hmat msg_hmat t ierr_t msg_t x ierr_x msg_x i j k t_max t_min x_max x_min
Variables
Type Attributes Name Initial
integer, parameter :: T_NUM = 201
integer, parameter :: X_NUM = 21
real(kind=dp) :: cfl
real(kind=dp) :: dt
real(kind=dp), dimension(:), allocatable :: h
integer :: ierr_h
character(len=120) :: msg_h
real(kind=dp), dimension(:), allocatable :: h_new
integer :: ierr_h_new
character(len=120) :: msg_h_new
real(kind=dp), dimension(:,:), allocatable :: hmat
integer :: ierr_hmat
character(len=120) :: msg_hmat
real(kind=dp), dimension(:), allocatable :: t
integer :: ierr_t
character(len=120) :: msg_t
real(kind=dp), dimension(:), allocatable :: x
integer :: ierr_x
character(len=120) :: msg_x
integer :: i
integer :: j
real(kind=dp) :: k
real(kind=dp) :: t_max
real(kind=dp) :: t_min
real(kind=dp) :: x_max
real(kind=dp) :: x_min
Call graph
fd1d_heat_explicit_prb calls fd1d_heat_explicit_cfl, r8mat_write, r8vec_write, r8vec_linspace